name: Deploy-dev

on:
  push:
    branches: [ "develop" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/ ;
        echo "$DEPLOY_SSH_PRIVATE_KEY" > ~/.ssh/deploy_key ;
        chmod 600 ~/.ssh/deploy_key ;
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts ;
      shell: bash
      env:
        DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Deploy to server
      run: |
        ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "mkdir -p /app/develop/trunk.new" 
        scp -i ~/.ssh/deploy_key -r ./* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }}:/app/develop/trunk.new
        ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "
          rm -r /app/develop/trunk.old
          mv /app/develop/trunk /app/develop/trunk.old && 
          mv /app/develop/trunk.new /app/develop/trunk &&
          cd /app/develop/trunk"
        ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} 'printf "${{ secrets.MATOMO_ENV }}" > /app/develop/trunk/.env'
        ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} 'printf "${{ secrets.FRIENDLYCAPTCHA_ENV }}" >> /app/develop/trunk/.env'
        ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "cd /app/develop/trunk && ls -lah"
      shell: bash
      env:
        DEPLOY_IP: ${{ secrets.DEPLOY_IP }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        MATOMO_ENV: ${{ secrets.MATOMO_ENV }}
        FRIENDLYCAPTCHA_ENV: ${{ secrets.FRIENDLYCAPTCHA_ENV }}
    - name: Run docker
      run: |
        ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "
        cd /app/develop/trunk &&
        mv docker-compose.yml docker-compose.prod.yml &&
        mv docker-compose.dev.yml docker-compose.yml &&
        docker container prune -f &&
        docker compose build &&
        docker compose down &&
        docker compose up -d;
        "
      shell: bash
      env:
        DEPLOY_IP: ${{ secrets.DEPLOY_IP }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
    - name: Validate deployment of llm-service
      working-directory: ./.github
      env:
        HTTP_AUTHORIZATION: ${{ secrets.HTTP_AUTHORIZATION }}
        CAPTCHA_OVERRIDE_SECRET: ${{ secrets.CAPTCHA_OVERRIDE_SECRET }}
      run: |
        ls -lah &&
        pip install requests &&
        python ci-test-dev.py 
